### ISSUE TITLE
请问这个报错是怎么回事？

### ISSUE THREAD

**Issue by bitmasterv** [cogons/pet-chain#11]
mac 中 node index.js 报下面错误，请问这个报错是怎么回事？

module.js:538
throw err;
^

Error: Cannot find module 'request'
at Function.Module._resolveFilename (module.js:536:15)
at Function.Module._load (module.js:466:25)
at Module.require (module.js:579:17)
at require (internal/module.js:11:18)
at Object. (/Users/dily/Documents/pet-chain/baidu_ocr/http/httpClient.js:17:17)
at Module._compile (module.js:635:30)
at Object.Module._extensions..js (module.js:646:10)
at Module.load (module.js:554:32)
at tryModuleLoad (module.js:497:12)
at Function.Module._load (module.js:489:3)

**Comment by iinitd** [comment]
先运行 npm install 再执行 node index.js
