### ISSUE TITLE
node index.js报错

### ISSUE THREAD

**Issue by Tomas-lee-git** [cogons/pet-chain#13]
C:\Users\Administrator\Desktop\pet-chain-master\index.js:66
(async function() {
       ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

**Comment by Tomas-lee-git** [comment]
看之前有人提到解决方法，我升级一下node版本

**Comment by iinitd** [comment]
好咧~
