### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by luoo369** [cogons/pet-chain#5]
E:\nodejs\etc\pet-chain-master>node index.js
E:\nodejs\etc\pet-chain-master\index.js:46
(async function() {
       ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

E:\nodejs\etc\pet-chain-master>

这个怎么弄？ 报错

**Comment by iinitd** [comment]
将node升级到最新稳定版

**Comment by luoo369** [comment]
谢谢

**Comment by iinitd** [comment]
不客气
