### ISSUE TITLE
报错：SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by TTQ99** [cogons/pet-chain#7]
把node升级到7.6以上

**Comment by iinitd** [comment]
可否附上具体报错信息🤔

**Comment by TTQ99** [comment]
async function () {

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

低版本node不支持async

**Comment by iinitd** [comment]
多谢提醒
