### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by tangtang666** [cogons/pet-chain#8]
E:\下载\360极速浏览器下载\pet-chain-master>node index.js
module.js:538
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\下载\360极速浏览器下载\pet-chain-master\baidu_ocr\
http\httpClient.js:17:17)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

**Comment by iinitd** [comment]
需要先执行npm install或是yarn~

**Comment by tangtang666** [comment]
npm install  后可以了

**Comment by iinitd** [comment]
好咧
