### ISSUE TITLE
改成手动模式还是会自动查找？   

### ISSUE THREAD

**Issue by wilburli** [cogons/pet-chain#9]
改成手动模式还是会自动查找？   都没机会输入验证码  debug时发现 fs.writeFileSync 这一步报异常了

**Comment by iinitd** [comment]
没有写入权限？项目换个地方试试呢

**Comment by wilburli** [comment]
我用管理员权限试过也没有成功 目前项目是在E盘  我改下文件夹权限吧

**Comment by wilburli** [comment]
这一句报错了![image](https://user-images.githubusercontent.com/13116043/35959778-f4e1593e-0ce1-11e8-9e5c-07c0b6f795c4.png)

**Comment by wilburli** [comment]
这个有配置错误吗![image](https://user-images.githubusercontent.com/13116043/35959860-542fb8ea-0ce2-11e8-93f0-4a7175e20a80.png)

**Comment by iinitd** [comment]
把 https://pet-chain.baidu.com/ 的 document.cookie 完整复制过去试试~
我的 cookie 信息还挺长的

**Comment by wilburli** [comment]
cookie 已经改了 还是有这个问题  应该是获取不到验证图片吧

**Comment by iinitd** [comment]
emmmm 看图片确实是验证码接口返回 error 了……
但是我这边使用是正常的，所以得看看你那边还有没有其他有用的信息，我再想一想😂

**Comment by 798066026** [comment]
我这边也是设置为手动，找到合适对象后无法停下来

**Comment by iinitd** [comment]
大概都是卡在验证码获取了…稍等我试一下

**Comment by 798066026** [comment]
![qq 20180208165813](https://user-images.githubusercontent.com/30956502/35961668-d47f0866-0cf1-11e8-8d6f-ec7906aee00b.png)
上个图，可能有帮助
另外，似乎品种等级有6个，不止5个

**Comment by bitmasterv** [comment]
请问这个报错是怎么回事？

module.js:538
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/dily/Documents/pet-chain/baidu_ocr/http/httpClient.js:17:17)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
